[package]
name = "rfid-blackjack-server"
version = "0.1.0"
edition = "2024"

[dependencies]
redis = "0.32.5"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
uuid = "1.18.1"
